### ISSUE TITLE
how can i use the c64 app?

### ISSUE THREAD

**Issue by IAMSolaara** [jeff-1amstudios/gif-to-c64-sprites#2]
i try to compile the app with several assemblers but none work... is this still maintained or the developer discontinued support?

**Comment by athomic1** [comment]
Haven't seen a response to the issue I raised a few months back, so I can't say the project is getting much attention.

I don't remember if I tried assembling the *.asm files. Which assemblers have you tried? Can you post any output logs? I'm assuming you're targeting the 6502 processor, yes?

**Comment by IAMSolaara** [comment]
I tried fasm, nasm, cbm prg studio... i'm gonna try xa now

**Comment by IAMSolaara** [comment]
I'm a noob in Assembler

**Comment by IAMSolaara** [comment]
and i'm using Ubuntu MATE 17.04

**Comment by athomic1** [comment]
Well, looking over the list you put up, XA is probably a step in the right direction.

FASM and NASM are both apparently x86 assemblers. They wouldn't recognize the 6502 mnemonics, so probably failed straight off. What you need is either a cross-assembler cabable of assembling 6502 code, or an actual 6502 assembler.

CBM prg Studio might have done the trick, if properly set up. I've never seen this kit before, and don't know just how it works, but assuming it includes a suitable assembler, I would think it should process the .asm files correctly. Again, though, I don't know how you're supposed to do that.

XA IS a 6502 cross-assembler, so I would expect it to work just fine, assuming the .asm files themselves are correct. I really haven't messed with any of this, so I can't tell you what to expect, but give it a shot, and let us know what happens.

**Comment by IAMSolaara** [comment]
in fact XA worked. i forgot to write.
gonna close the issue
